### ISSUE TITLE
Allow configure path & table name for migrations 

### ISSUE THREAD

**Issue by vtsykun** [okvpn/migration-bundle#17]
Currently there is no way to specify the custom path that located migration files, because it is hardcoded in [code](https://github.com/okvpn/migration-bundle/blob/master/src/Migration/Loader/MigrationsLoader.php#L28) 
Simple configuration for it should looks like: 

```yml 
#config.yml

okvpn_migration:
    migrations_path: 'Migrations/Schema'
    migrations_table: 'my_migrations'
```
